### PR TITLE
Adding port option

### PR DESCRIPTION
**Pull request by cmosh**
Done the TODO in assets.php to add port option in config.

### CODE REVIEW

**Comment by tortuetorche** [comment]
Hi @cmosh,

Thank you for this pull-request, but since Larasset 1.1, the `port` option is configurable, see [this commit](https://github.com/efficiently/larasset/commit/941cb6a3b6cf632121d29e73b96238fa7067b7dd).
Your pull-request is for the Larasset 1.0 branch, but the 1.1 branch should be backward compatible with the 1.0 branch.
So, do you have a particular reason for backporting this feature in the 1.0 branch?

Cheers,
Tortue Torche

**Comment by cmosh** [comment]
This is because I'm currently working on a laravel 5.0 project and wasn't sure if the 1.1 branch is fully compatible with it.

**Comment by tortuetorche** [comment]
I see, I don't have application build with Laravel 5.0 anymore.
I use Larasset with Laravel 4.2 and 5.1, but it should be OK with Laravel 5.0
If you have any troubles with it, I'll backporting the `port` feature on the 1.0 branch.

**Comment by cmosh** [comment]
Thank you for the quick response, I'll try using the 1.1 branch and let you know if I have any problems.

**Comment by tortuetorche** [comment]
You're welcome.
Maybe I should tag and publish a `1.1.0` version for the 1.1 branch...

**Comment by cmosh** [comment]
I don't think I'm the only one who'd appreciate it if you did.

**Comment by tortuetorche** [comment]
Done :sunglasses:!
https://github.com/efficiently/larasset/tree/1.1.0

**Comment by cmosh** [comment]
Awesome! 
I'd also like to confirm that it works with laravel 5.0 perfectly.
Thanks again.

**Pull request closed without merging**
